### ISSUE TITLE
Help with implementing netlify local fs backend with gatsby js

### ISSUE THREAD

**Issue by 5-11** [talves/netlify-cms-backend-fs#1]
Hi @talves,

I'am trying to implement your local fs backend with my gatsby js project. I followed your steps but I am not sure what to do with 4. suggested step ([Webpack] Add devServer middleware to expose the /api path for the file-system API) especially in case of gatsby project. Can you give me some insights on this one please?

Thank you for your time and writing this plugin.

**Comment by talves** [comment]
***Opinion:*** I can point you in the right direction, but I will not be able to give the solution example. I do not like Gatsby for this reason and have spent hours trying to figure out their magic box setup to configure it correctly for other simple things with too many roadblocks.

***Setup Needed:***

- Must extend the devServer Middleware:  
-  [fs-express-api](https://github.com/talves/netlify-cms-backend-fs/blob/master/scripts/fs/fs-express-api.js) needs to exist in your project repo, so copy over the whole `scripts/fs` folder to the repo you are using the new backend.  You will need both of these in your repo to spin up the api.
- In your dev webpack config you need to add the middleware (fs-express-api) to the devServer

Code to implement in a normal webpack devServer Setup:

Import the fs-express-api into your webpack config

    const fileSystemAPIPlugin = require('./scripts/fs/fs-express-api');

Add to the webpack devServer setup or add one into your build

```
   devServer: {
     contentBase: 'example/',
     historyApiFallback: true,
     disableHostCheck: true,
     headers: {"Access-Control-Allow-Origin": "*"},
+    before: fileSystemAPIPlugin,
   },
```

***Other Option:*** (Requires knowledge)

Create a script to spin up an express server on a different port and use that as the api root (i.e. `api_root: http://localhost:8090/api`)

**Comment by 5-11** [comment]
Hi @talves,

Thank you for your time, help and instructions. I managed to solve this by choosing the latter option. I will write down my solution/modification step by step in case anyone else would need this.

1. I created an express server in my Gatsby Js project that runs on the same url and port as defined in src/implementation.js file of this plugin.

```
this.api_root = config.getIn(["backend", "api_root"], "http://localhost:8080/api");`
```
2. I implemented the fs-express-api middleware 

3. Set the right path to the folder where you keep your md and media files in fs-api.js file that you copied in your server folder.

```
const projectRoot = path.join(__dirname, '../../../../');
```
4. Optional step would be to increase limit of maximum request body size if you would like to upload larger files.

That is it...you should be able now to run your netlify CMS with local file-system backend.

**Comment by talves** [comment]
#4 The easiest way to extend for larger files size is to use `multer`.

**[I created a create-react-app starter example](https://github.com/talves/netlify-cms-react-example) to use to extend the cms and create a build bundle that does not require a separate terminal or express server. **
